### ISSUE TITLE
Duplicate of Test Steps

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#547] opened 2015-07-13 03:22 UTC
In Network Testing project

Test Step "Confirm DUT is connected" is duplicated 3 times.

Test step should not be duplicated with the same name

**Comment by riz-hossain** [comment] 2015-07-13 05:24
That's really strange... how is it possible? Once you create a step, as you type, it should just come automatically and you should be able to just select it right? Unless! You created the test case for the very first time and in that test case you used new steps name twice... that might result in that.  So solution would be that before we create a step, we need to verify that same step does not exists. Minar this is yours I think.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: matariqSent: Sunday, July 12, 2015 11:22 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] Duplicate of Test Steps (#547)In Network Testing project

Test Step "Confirm DUT is connected" is duplicated 3 times.

Test step should not be duplicated with the same name

—Reply to this email directly or view it on GitHub.

**Comment by minar09** [comment] 2015-07-14 10:03
Please check now!

**Comment by riz-hossain** [comment] 2015-07-15 00:05
Please verify and if possible outline how it was reproduced

**Comment by matariq** [comment] 2015-07-15 02:36
I cannot reproduce it but if you go in Network Testing project - Test Step "Confirm DUT is connected" is duplicated 3 times.

Can you please remove the duplicate 2 for now?

**Comment by m3thun** [comment] 2015-08-26 03:51
@riz-hossain copied and closing!

**Closed** 2015-08-30 01:15 UTC
Labels: bug, Done, Minar, Priority 2 (High), Started
