### ISSUE TITLE
Project Management Part

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#370] opened 2015-02-06 03:06 UTC
As Multiple Project Demo were coming, it was very annoying for me to manually add all the things in the Database. Here is the flow that one should go to make a automation project run in their pc:

1.Admin will create a project and set an owner.
2.Project owner will go to project page and create some team and add them to their projects.
3.Each of the user that are created should assign themselves with the default settings
4.Then feature and section linking of the project should be done
5. Dependency, Version will have to linked.
6. Test Cases should be created.
7. login_info.py file under AutomatinoFW will be changed by a authentication of the project owner.

Done Points are:
1, 5

Undone points are:
2, 3,4(feature should add all the child if one parents are linked and for section linking we need some advice from @sazid )
6 (searching of the test case in test case creation page is not done by team and project) 
7 login_info.py will have to be changed manually.

**Comment by Taitalus** [comment] 2015-02-06 03:07
@raqbo  and @riz-hossain  please all the requirements are fulfilled.

**Comment by riz-hossain** [comment] 2015-02-06 03:15
on latest db, i dont see any project under me ..
i only see project 28



On Thu, Feb 5, 2015 at 10:06 PM, Raju Ahmed Shetu <notifications@github.com>
wrote:

> As Multiple Project Demo were coming, it was very annoying for me to
> manually add all the things in the Database. Here is the flow that one
> should go to make a automation project run in their pc:
>
> 1.Admin will create a project and set an owner.
> 2.Project owner will go to project page and create some team and add them
> to their projects.
> 3.Each of the user that are created should assign themselves with the
> default settings
> 4.Then feature and section linking of the project should be done
> 5. Dependency, Version will have to linked.
> 6. Test Cases should be created.
> 7. login_info.py file under AutomatinoFW will be changed by a
> authentication of the project owner.
>
> Done Points are:
> 1, 5
>
> Undone points are:
> 2, 3,4(feature should add all the child if one parents are linked and for
> section linking we need some advice from @sazid <https://github.com/sazid>
> )
> 6 (searching of the test case in test case creation page is not done by
> team and project)
> 7 login_info.py will have to be changed manually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/370>.
>



-- 

Riz Hossain
Engineering Physics (B.Eng)
Automation Test Lead
Research In Motion
295 Phillip Street
Waterloo, ON N2L 3L3


This transmission (including any attachments) may contain confidential
information, privileged material (including material protected by the
solicitor-client or other applicable privileges), or constitute non-public
information. Any use of this information by anyone other than the intended
recipient is prohibited. If you have received this transmission in error,
please immediately reply to the sender and delete this information from
your system. Use, dissemination, distribution, or reproduction of this
transmission by unintended recipients is not authorized and may be unlawful.

**Comment by Taitalus** [comment] 2015-02-06 03:17
login with rizu and .

**Comment by Taitalus** [comment] 2015-02-08 13:00
point no 3. and feature of point 4 is done. going for the 2.

**Comment by m3thun** [comment] 2015-08-28 22:58
@riz-hossain copied and closing!

**Closed by m3thun** 2015-08-28 22:58 UTC
Labels: Priority 1 (Highest), Requirements, Shetu
